all:
			make -C debugging all
			make -C rawIO13 all
			make -C sofs13 all
			make -C showBlock13 all
			make -C mkfs13 all
			make -C testifuncs13 all
			make -C mount13 all

clean:
			make -C debugging clean
			make -C rawIO13 clean
			make -C sofs13 clean
			make -C showBlock13 clean
			make -C mkfs13 clean
			make -C testifuncs13 clean
			make -C mount13 clean

